apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  BASE_URL_SERVICE_1: "https://dev.matveyguralskiy.com"
  BASE_URL_SERVICE_2: "https://dev.matveyguralskiy.com"
  BASE_URL_SERVICE_3: "https://dev.matveyguralskiy.com"
  BASE_URL_SERVICE_4: "https://dev.matveyguralskiy.com"
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'node'
        static_configs:
          - targets: ['node-exporter:9100']
