#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    env: {{ .Values.env }}
    type: Website
    owner: Matvey_Guralskiy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        {{- range $key, $value := .Values.microservices }}
        - name: {{ $key }}-container
          image: {{ $value.container.image }}
          ports:
            - containerPort: 80
        {{- end }}