#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: grafana
  type: ClusterIP
