#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: {{ .Values.namespace }}
data:
  grafana.ini: |
    [server]
    root_url = http://grafana.matveyguralskiy.com
    serve_from_sub_path = true
    [auth]
    disable_login_form = false
    disable_signout_menu = false
