#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.microservices.main.deploymentName }}
  namespace: {{ .Values.namespace }}
  labels:
    type: Website
    owner: Matvey_Guralskiy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: main-service
  template:
    metadata:
      labels:
        app: main-service
    spec:
      containers:
        - name: main-container
          image: {{ .Values.microservices.main.container.image }}
          ports:
            - containerPort: {{ .Values.microservices.main.container.port }}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret_access_key
            - name: BASE_URL_SERVICE_1
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BASE_URL_SERVICE_1
            - name: BASE_URL_SERVICE_2
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BASE_URL_SERVICE_2
            - name: BASE_URL_SERVICE_3
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BASE_URL_SERVICE_3
            - name: BASE_URL_SERVICE_4
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BASE_URL_SERVICE_4
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: SECRET_KEY
            - name: SESSION_COOKIE_SECURE
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: SESSION_COOKIE_SECURE
            - name: SESSION_COOKIE_HTTPONLY
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: SESSION_COOKIE_HTTPONLY
            - name: SESSION_COOKIE_SAMESITE
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: SESSION_COOKIE_SAMESITE