#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.microservices.main.deploymentName }}
  namespace: {{ .Values.namespace }}
  labels:
    type: Website
    owner: Matvey_Guralskiy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-service
  template:
    metadata:
      labels:
        app: main-service
    spec:
      containers:
        - name: main-container
          image: {{ .Values.microservices.main.container.image }}
          ports:
            - containerPort: 80
          env:
            - name: BASE_URL_SERVICE_1
              value: "{{ .Values.microservices.main.base_url }}"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: SECRET_KEY
            - name: SESSION_COOKIE_SECURE
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: SESSION_COOKIE_SECURE
            - name: SESSION_COOKIE_HTTPONLY
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: SESSION_COOKIE_HTTPONLY
            - name: SESSION_COOKIE_SAMESITE
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: SESSION_COOKIE_SAMESITE