#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------
apiVersion: v1
kind: Service
metadata:
  name: main-service
  namespace: {{ .Values.namespace }}
  labels:
    env: {{ .Values.env | quote }}
    type: Website
    owner: Matvey_Guralskiy
spec:
  selector:
    app: main-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP