#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-monitoring
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: monitor-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
