#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.microservices.players.deploymentName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: players-service
    env: {{ .Values.env | quote }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: players-service
  template:
    metadata:
      labels:
        app: players-service
    spec:
      containers:
        - name: players-container
          image: {{ .Values.microservices.players.container.image }}
          ports:
            - containerPort: 80
          env:
            - name: BASE_URL
              value: "{{ .Values.microservices.players.base_url | quote }}"
            {{- range .Values.env }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
            {{- end }}
