apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data/prometheus
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-prometheus-alertmanager-0
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data/prometheus-alertmanager
  storageClassName: manual
