#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------
apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
  namespace: dribbledata-project
type: Opaque
data:
  SECRET_KEY: <base64-encoded-secret-key>
  DAX_ENDPOINT: <base64-encoded-dax-endpoint>
  SESSION_COOKIE_SECURE: <base64-encoded-session-cookie-secure>
  SESSION_COOKIE_HTTPONLY: <base64-encoded-session-cookie-httponly>
  SESSION_COOKIE_SAMESITE: <base64-encoded-session-cookie-samesite>
  REPOSITORY_URI: <base64-encoded-repository-uri>