#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.microservices.training.deploymentName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: training-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: training-service
  template:
    metadata:
      labels:
        app: training-service
    spec:
      containers:
        - name: training-container
          image: {{ .Values.microservices.training.container.image }}
          ports:
            - containerPort: 80
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret_access_key
            - name: BASE_URL_SERVICE_3
              value: "{{ .Values.microservices.main.base_url }}"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: SECRET_KEY
            - name: SESSION_COOKIE_SECURE
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: SESSION_COOKIE_SECURE
            - name: SESSION_COOKIE_HTTPONLY
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: SESSION_COOKIE_HTTPONLY
            - name: SESSION_COOKIE_SAMESITE
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: SESSION_COOKIE_SAMESITE