#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: users-service
    env: {{ .Values.env }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-container
          image: {{ .Values.microservices.users.container.image }}
          ports:
            - containerPort: 80
          env:
            - name: BASE_URL
              value: "{{ .Values.microservices.users.base_url }}"