#---------------------------
#DribbleData Project
#Created by Matvey Guralskiy
#---------------------------
version: '3.8'

services:
  main:
    build: ./main
    ports:
      - "5000:5000"
    env_file:
      - .env
  users:
    build: ./users
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ~/.aws:/root/.aws:ro

  training:
    build: ./training
    ports:
      - "5002:5002"
    env_file:
      - .env
    volumes:
      - ~/.aws:/root/.aws:ro

  players:
    build: ./players
    ports:
      - "5003:5003"
    env_file:
      - .env
    volumes:
      - ~/.aws:/root/.aws:ro
