#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------

# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run Gunicorn server
CMD ["gunicorn", "-b", "0.0.0.0:5000", "-t", "120", "app:app"]
