#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------
version: '3.8'

services:
  main:
    image: matveyguralskiy/dribbledata_main:${IMAGE_VERSION}
    ports:
      - "8000:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  users:
    image: matveyguralskiy/dribbledata_users:${IMAGE_VERSION}
    ports:
      - "8001:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  training:
    image: matveyguralskiy/dribbledata_training:${IMAGE_VERSION}
    ports:
      - "8002:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  players:
    image: matveyguralskiy/dribbledata_players:${IMAGE_VERSION}
    ports:
      - "8003:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
