#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------
namespace: dribbledata-project
env: Development

# Common settings for all microservices
replicaCount: 4
image:
  tag: V2.1

# Configuration for each microservice
microservices:
  main:
    deploymentName: main
    container:
      image: matveyguralskiy/dribbledata_main:V2.1
      port: 80
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb
    ingressPath: /
    base_url: http://dev.matveyguralskiy.com
    env:
      - name: BASE_URL_SERVICE_1
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_1
      - name: BASE_URL_SERVICE_2
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_2
      - name: BASE_URL_SERVICE_3
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_3
      - name: BASE_URL_SERVICE_4
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_4

  users:
    deploymentName: users
    container:
      image: matveyguralskiy/dribbledata_users:V2.1
      port: 80
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb
    ingressPath: /register
    base_url: http://dev.matveyguralskiy.com
    env:
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SECRET_KEY
      - name: SESSION_COOKIE_SECURE
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_SECURE
      - name: SESSION_COOKIE_HTTPONLY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_HTTPONLY
      - name: SESSION_COOKIE_SAMESITE
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_SAMESITE
      - name: BASE_URL_SERVICE_1
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_1
      - name: BASE_URL_SERVICE_2
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_2
      - name: BASE_URL_SERVICE_3
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_3
      - name: BASE_URL_SERVICE_4
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_4

  training:
    deploymentName: training
    container:
      image: matveyguralskiy/dribbledata_training:V2.1
      port: 80
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb
    ingressPath: /training
    base_url: http://dev.matveyguralskiy.com
    env:
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SECRET_KEY
      - name: SESSION_COOKIE_SECURE
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_SECURE
      - name: SESSION_COOKIE_HTTPONLY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_HTTPONLY
      - name: SESSION_COOKIE_SAMESITE
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_SAMESITE
      - name: BASE_URL_SERVICE_1
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_1
      - name: BASE_URL_SERVICE_2
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_2
      - name: BASE_URL_SERVICE_3
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_3
      - name: BASE_URL_SERVICE_4
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_4

  players:
    deploymentName: players
    container:
      image: matveyguralskiy/dribbledata_players:V2.1
      port: 80
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb
    ingressPath: /players
    base_url: http://dev.matveyguralskiy.com
    env:
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SECRET_KEY
      - name: SESSION_COOKIE_SECURE
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_SECURE
      - name: SESSION_COOKIE_HTTPONLY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_HTTPONLY
      - name: SESSION_COOKIE_SAMESITE
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_SAMESITE
      - name: BASE_URL_SERVICE_1
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_1
      - name: BASE_URL_SERVICE_2
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_2
      - name: BASE_URL_SERVICE_3
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_3
      - name: BASE_URL_SERVICE_4
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_4

prometheus:
  deploymentName: prometheus-server
  container:
    image: prom/prometheus:latest
    port: 9090
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: alb
  ingressPath: /
  base_url: http://prometheus.matveyguralskiy.com


awsLoadBalancerController:
  image:
    repository: public.ecr.aws/eks/aws-load-balancer-controller
    tag: v2.8.1
    pullPolicy: IfNotPresent
  clusterName: EKS-Development
  region: us-east-1
  vpcId: vpc-07e14b6f685ea7fcc
  serviceAccount:
    create: true
    name: aws-load-balancer-controller
    annotations: {}
    labels: {}
  defaultTags:
    k8s-cluster: eks-cluster
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    externalTrafficPolicy: Cluster
  podSecurityPolicy:
    enabled: false

subnets:
  - id: subnet-003e561e6466f60a9
    tags:
      - key: kubernetes.io/role/elb
        value: 1
  - id: subnet-087142893aed4ba37
    tags:
      - key: kubernetes.io/role/elb
        value: 1

ingress:
  host: dev.matveyguralskiy.com
  tlsSecretName: tls-secret
  certificateArn: arn:aws:acm:us-east-1:381491938951:certificate/8c482ba1-e70f-41b4-974d-d6273dacc4a1
  
  host2: prometheus.matveyguralskiy.com
  tlsSecretName2: prometheus-tls-secret
  certificateArn2: arn:aws:acm:us-east-1:381491938951:certificate/8c482ba1-e70f-41b4-974d-d6273dacc4a1
  service2: prometheus-service
