#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------
namespace: dribbledata-project
env: Development

# Common settings for all microservices
replicaCount: 4
image:
  tag: V0.8

# Configuration for each microservice
microservices:
  main:
    deploymentName: main
    container:
      image: matveyguralskiy/dribbledata_main:{{ .Values.image.tag }}
      port: 80
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb
    ingressPath: /
    base_url: http://dev.matveyguralskiy.com

  users:
    deploymentName: users
    container:
      image: matveyguralskiy/dribbledata_users:{{ .Values.image.tag }}
      port: 80
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb
    ingressPath: /register
    base_url: http://dev.matveyguralskiy.com
    env:
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SECRET_KEY
      - name: SESSION_COOKIE_SECURE
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_SECURE
      - name: SESSION_COOKIE_HTTPONLY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_HTTPONLY
      - name: SESSION_COOKIE_SAMESITE
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_SAMESITE

  training:
    deploymentName: training
    container:
      image: matveyguralskiy/dribbledata_training:{{ .Values.image.tag }}
      port: 80
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb
    ingressPath: /training
    base_url: http://dev.matveyguralskiy.com
    env:
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SECRET_KEY
      - name: SESSION_COOKIE_SECURE
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_SECURE
      - name: SESSION_COOKIE_HTTPONLY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_HTTPONLY
      - name: SESSION_COOKIE_SAMESITE
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_SAMESITE

  players:
    deploymentName: players
    container:
      image: matveyguralskiy/dribbledata_players:{{ .Values.image.tag }}
      port: 80
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb
    ingressPath: /players
    base_url: http://dev.matveyguralskiy.com
    env:
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SECRET_KEY
      - name: SESSION_COOKIE_SECURE
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_SECURE
      - name: SESSION_COOKIE_HTTPONLY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_HTTPONLY
      - name: SESSION_COOKIE_SAMESITE
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_SAMESITE

awsLoadBalancerController:
  image:
    repository: public.ecr.aws/eks/aws-load-balancer-controller
    tag: v2.8.1
    pullPolicy: IfNotPresent
  clusterName: EKS-Development
  region: us-east-1
  vpcId: vpc-0496451e98e05d8b4
  serviceAccount:
    create: true
    name: aws-load-balancer-controller
    annotations: {}
    labels: {}
  defaultTags:
    k8s-cluster: eks-cluster
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    externalTrafficPolicy: Cluster
  podSecurityPolicy:
    enabled: false

subnets:
  - id: subnet-070dc5c2adb662e01
    tags:
      - key: kubernetes.io/role/elb
        value: 1
  - id: subnet-02119eb443c3825d0
    tags:
      - key: kubernetes.io/role/elb
        value: 1

ingress:
  host: dev.matveyguralskiy.com
  tlsSecretName: tls-secret
  certificateArn: arn:aws:acm:us-east-1:381491938951:certificate/81faa0d2-5cfe-4c34-a17c-72553d2af5ac