#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------
namespace: dribbledata-project
env: Production

# Common settings for all microservices
replicaCount: 4
image:
  tag: V4.8

# Configuration for each microservice
microservices:
  main:
    deploymentName: main
    container:
      image: matveyguralskiy/dribbledata_main:V4.8
      port: 80
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb
    ingressPath: /
    base_url: dribbledata.matveyguralskiy.com
    env:
      - name: BASE_URL_SERVICE_1
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_1
      - name: BASE_URL_SERVICE_2
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_2
      - name: BASE_URL_SERVICE_3
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_3
      - name: BASE_URL_SERVICE_4
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_4

  users:
    deploymentName: users
    container:
      image: matveyguralskiy/dribbledata_users:V4.8
      port: 80
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb
    ingressPath: /register
    base_url: dribbledata.matveyguralskiy.com
    env:
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SECRET_KEY
      - name: SESSION_COOKIE_SECURE
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_SECURE
      - name: SESSION_COOKIE_HTTPONLY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_HTTPONLY
      - name: SESSION_COOKIE_SAMESITE
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_SAMESITE
      - name: BASE_URL_SERVICE_1
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_1
      - name: BASE_URL_SERVICE_2
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_2
      - name: BASE_URL_SERVICE_3
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_3
      - name: BASE_URL_SERVICE_4
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_4

  training:
    deploymentName: training
    container:
      image: matveyguralskiy/dribbledata_training:V4.8
      port: 80
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb
    ingressPath: /training
    base_url: dribbledata.matveyguralskiy.com
    env:
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SECRET_KEY
      - name: SESSION_COOKIE_SECURE
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_SECURE
      - name: SESSION_COOKIE_HTTPONLY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_HTTPONLY
      - name: SESSION_COOKIE_SAMESITE
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_SAMESITE
      - name: BASE_URL_SERVICE_1
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_1
      - name: BASE_URL_SERVICE_2
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_2
      - name: BASE_URL_SERVICE_3
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_3
      - name: BASE_URL_SERVICE_4
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_4

  players:
    deploymentName: players
    container:
      image: matveyguralskiy/dribbledata_players:V4.8
      port: 80
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb
    ingressPath: /players
    base_url: dribbledata.matveyguralskiy.com
    env:
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SECRET_KEY
      - name: SESSION_COOKIE_SECURE
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_SECURE
      - name: SESSION_COOKIE_HTTPONLY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_HTTPONLY
      - name: SESSION_COOKIE_SAMESITE
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: SESSION_COOKIE_SAMESITE
      - name: BASE_URL_SERVICE_1
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_1
      - name: BASE_URL_SERVICE_2
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_2
      - name: BASE_URL_SERVICE_3
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_3
      - name: BASE_URL_SERVICE_4
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BASE_URL_SERVICE_4

prometheus:
  deploymentName: prometheus-server
  container:
    image: prom/prometheus:latest
    port: 9090
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: alb
  ingressPath: /
  base_url: prometheus.matveyguralskiy.com

grafana:
  enabled: true
  adminPassword: "admin"
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    name: grafana-ingress
    path: /
    hosts:
      - grafana.matveyguralskiy.com
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.matveyguralskiy.com
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

awsLoadBalancerController:
  image:
    repository: public.ecr.aws/eks/aws-load-balancer-controller
    tag: v2.8.1
    pullPolicy: IfNotPresent
  clusterName: EKS-Dribbledata
  region: us-east-1
  vpcId: vpc-00c5619e2ecf47950
  serviceAccount:
    create: true
    name: aws-load-balancer-controller
    annotations: {}
    labels: {}
  defaultTags:
    k8s-cluster: eks-cluster
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    externalTrafficPolicy: Cluster
  podSecurityPolicy:
    enabled: false

subnets:
  - id: subnet-0c327f709d647ed4b
    tags:
      - key: kubernetes.io/role/elb
        value: 1
  - id: subnet-0fa4b065830cb4e0c
    tags:
      - key: kubernetes.io/role/elb
        value: 1


nodeExporter:
  enabled: true
  service:
    enabled: true
    type: ClusterIP
  daemonSet:
    enabled: true
    updateStrategy:
      type: RollingUpdate
    nodeSelector: {}
    tolerations: []
    affinity: {}

ingress:
  host: dribbledata.matveyguralskiy.com
  tlsSecretName: tls-secret
  certificateArn: arn:aws:acm:us-east-1:381491938951:certificate/41ce9ab3-7fb6-4fc9-840b-474e4b072b3a
  
  host2: prometheus.matveyguralskiy.com
  tlsSecretName2: prometheus-tls-secret
  certificateArn2: arn:aws:acm:us-east-1:381491938951:certificate/d770be92-730b-4e09-93fd-2447672cff04

  host3: grafana.matveyguralskiy.com
  tlsSecretName3: grafana-tls-secret
  certificateArn3: arn:aws:acm:us-east-1:381491938951:certificate/ea3e55f7-934c-4109-aeeb-75f69581cb78
