#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------
namespace: dribbledata-project
env: Development

# Common settings for all microservices
replicaCount: 4
image:
  tag: V0.4

# Configuration for each microservice
microservices:
  main:
    deploymentName: main
    container:
      image: matveyguralskiy/dribbledata_main:V0.4
      port: 80
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb
    ingressPath: /
    base_Url: http://dev.matveyguralskiy.com

  users:
    deploymentName: users
    container:
      image: matveyguralskiy/dribbledata_users:V0.4
      port: 80
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb
    ingressPath: /users
    base_Url: http://dev.matveyguralskiy.com/users

  training:
    deploymentName: training
    container:
      image: matveyguralskiy/dribbledata_training:V0.4
      port: 80
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb
    ingressPath: /training
    base_Url: http://dev.matveyguralskiy.com/training

  players:
    deploymentName: players
    container:
      image: matveyguralskiy/dribbledata_players:V0.4
      port: 80
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb
    ingressPath: /players
    base_Url: http://dev.matveyguralskiy.com/players

awsLoadBalancerController:
  image:
    repository: public.ecr.aws/eks/aws-load-balancer-controller
    tag: v2.8.1
    pullPolicy: IfNotPresent
  clusterName: EKS-Development
  region: us-east-1
  vpcId: vpc-0daf9b002806ae4dd
  serviceAccount:
    create: true
    name: aws-load-balancer-controller
    annotations: {}
    labels: {}
  defaultTags:
    k8s-cluster: eks-cluster
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    externalTrafficPolicy: Cluster
  podSecurityPolicy:
    enabled: false

subnets:
  - id: subnet-0800200e437ee7d86
    tags:
      - key: kubernetes.io/role/elb
        value: 1
  - id: subnet-0c0aedd168c564c17
    tags:
      - key: kubernetes.io/role/elb
        value: 1

ingress:
  host: dev.matveyguralskiy.com
  tlsSecretName: tls-secret
  certificateArn: arn:aws:acm:us-east-1:381491938951:certificate/98afd82b-7bb7-41ea-816c-4b71f3bcdfcd