#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------
replicaCount: 4

# Configuration for each microservice
microservices:
  main:
    container:
      image: matveyguralskiy/dribbledata_main:{{ .Values.images.main }}
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb

  users:
    container:
      image: matveyguralskiy/dribbledata_users:{{ .Values.images.users }}
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb

  training:
    container:
      image: matveyguralskiy/dribbledata_training:{{ .Values.images.training }}
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb

  players:
    container:
      image: matveyguralskiy/dribbledata_players:{{ .Values.images.players }}
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb

awsLoadBalancerController:
  image:
    repository: public.ecr.aws/eks/aws-load-balancer-controller
    tag: v2.8.1
    pullPolicy: IfNotPresent
  clusterName: EKS-Development
  region: us-east-1
  vpcId: vpc-052425a1c7fb91650
  serviceAccount:
    create: true
    name: aws-load-balancer-controller
    annotations: {}
    labels: {}
  defaultTags:
    k8s-cluster: eks-cluster
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    externalTrafficPolicy: Cluster
  podSecurityPolicy:
    enabled: false

subnets:
  - id: subnet-0f6d2a8d227e569df
    tags:
      - key: kubernetes.io/role/elb
        value: 1
  - id: subnet-0c10e6d20d7887272
    tags:
      - key: kubernetes.io/role/elb
        value: 1

ingress:
  host: dev.matveyguralskiy.com
  tlsSecretName: tls-secret
  certificateArn: arn:aws:acm:us-east-1:381491938951:certificate/7bb3830c-ba3c-4211-86f7-295e5f6031e9

namespace: dribbledata-project

env: Development

images:
  main: "v0.3"
  users: "v0.3"
  training: "v0.3"
  players: "v0.3"