#---------------------------
# DribbleData Project
# Created by Matvey Guralskiy
#---------------------------
replicaCount: 4

# Configuration for each microservice
microservices:
  main:
    container:
      image: matveyguralskiy/dribbledata_main:${IMAGE_VERSION}
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb

  users:
    container:
      image: matveyguralskiy/dribbledata_users:${IMAGE_VERSION}
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb

  training:
    container:
      image: matveyguralskiy/dribbledata_training:${IMAGE_VERSION}
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb

  players:
    container:
      image: matveyguralskiy/dribbledata_players:${IMAGE_VERSION}
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: alb

awsLoadBalancerController:
  image:
    repository: public.ecr.aws/eks/aws-load-balancer-controller
    tag: v2.8.1
    pullPolicy: IfNotPresent
  clusterName: EKS-FlaskPipeline
  region: us-east-1
  vpcId: YOUR_VPC_ID
  serviceAccount:
    create: true
    name: aws-load-balancer-controller
    annotations: {}
    labels: {}
  defaultTags:
    k8s-cluster: eks-cluster
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    externalTrafficPolicy: Cluster
  podSecurityPolicy:
    enabled: false

subnets:
  - id: YOUR_PUBLIC_A_ID
    tags:
      - key: kubernetes.io/role/elb
        value: 1
  - id: YOUR_PUBLIC_B_ID
    tags:
      - key: kubernetes.io/role/elb
        value: 1

ingress:
  host: dev.matveyguralskiy.com
  tlsSecretName: tls-secret
  certificateArn: arn:aws:acm:region:account-id:certificate/certificate-id

namespace: dribbledata-project

env: Production