name: CI/CD Pipeline DribbleData

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

  install-dependencies:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: List files in the working directory
      run: ls -ls
    
    - name: Install dependencies for main microservice
      run: |
        cd Application/main
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install dependencies for users microservice
      run: |
        cd Application/users
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install dependencies for training microservice
      run: |
        cd Application/training
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install dependencies for players microservice
      run: |
        cd Application/players
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  create-env:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
    - name: Create .env file
      run: |
        echo "SECRET_KEY=$(aws ssm get-parameter --name /dribble-data/SECRET_KEY --region $AWS_DEFAULT_REGION --query "Parameter.Value" --output text)" >> Application/.env
        echo "DAX_ENDPOINT=$(aws ssm get-parameter --name /dribble-data/DAX_ENDPOINT --region $AWS_DEFAULT_REGION --query "Parameter.Value" --output text)" >> Application/.env
        echo "SESSION_COOKIE_SECURE=$(aws ssm get-parameter --name /dribble-data/SESSION_COOKIE_SECURE --region $AWS_DEFAULT_REGION --query "Parameter.Value" --output text)" >> Application/.env
        echo "SESSION_COOKIE_HTTPONLY=$(aws ssm get-parameter --name /dribble-data/SESSION_COOKIE_HTTPONLY --region $AWS_DEFAULT_REGION --query "Parameter.Value" --output text)" >> Application/.env
        echo "SESSION_COOKIE_SAMESITE=$(aws ssm get-parameter --name /dribble-data/SESSION_COOKIE_SAMESITE --region $AWS_DEFAULT_REGION --query "Parameter.Value" --output text)" >> Application/.env
        echo "REPOSITORY_URI=$(aws ssm get-parameter --name /dribble-data/REPOSITORY_URI --region $AWS_DEFAULT_REGION --query "Parameter.Value" --output text)" >> Application/.env
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
      env:
        AWS_DEFAULT_REGION: us-east-1

  test:
    runs-on: ubuntu-latest
    needs: create-env
    steps:
    - name: Run unit tests
      run: |
        cd Application
        python -m unittest unit_tests.py

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build Docker Compose
      run: |
        cd Application
        docker-compose build

    - name: List Docker images
      run: docker images

    - name: Rename Docker images
      run: |
        docker tag application-main matveyguralskiy/dribbledata_main:latest
        docker tag application-users matveyguralskiy/dribbledata_users:latest
        docker tag application-training matveyguralskiy/dribbledata_training:latest
        docker tag application-players matveyguralskiy/dribbledata_players:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push matveyguralskiy/dribbledata_main:latest
        docker push matveyguralskiy/dribbledata_users:latest
        docker push matveyguralskiy/dribbledata_training:latest
        docker push matveyguralskiy/dribbledata_players:latest
